CREATE TABLE IF NOT EXISTS MESSAGE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MESSAGE VARCHAR(255)
);

INSERT INTO MESSAGE (MESSAGE) VALUES
('C Technology'),
('C++ Technology'),
('Java Technology'),
('Python Technology'),
('Java Script Technology'),
('Ruby Technology'),
('Perl Technology'),
('Spring Boot Technology'),
('Docker Technology'),
('Kubernetes Technology'),
('Ansible Technology'),
('Terraform Technology'),
('Jenkins Technology'),
('Maven Technology'),
('Gradle Technology'),
('Git Bash Technology'),
('Linux Technology'),
('Windows Technology'),
('Mac Technology'),
('SQL Technology'),
('No SQL Technology'),
('C# Technology'),
('Type Script Technology'),
('ReactJs Technology'),
('AngularJs Technology'),
('HTML Technology'),
('CSS Technology'),
('Bootstrap Technology'),
('JQuery Technology'),
('AJAX Technology'),
('Mockito Technology'),
('JUnit Technology'),
('Swagger Technology');
